### PR TITLE
Fix gnosis auto connect when not inside gnosis iframe

### LINKED ISSUE #29: Gnosis safe connector should only automatically connect inside safe iframe
> If you were connected to the snapshot app outside the Safe, it keeps the connection with the previous wallet. 
> We ask apps to auto-connect to the Safe when loaded in the Safe app context to minimize possible human errors.

After connecting using the Gnosis-safe connector the app no longer lets the user change wallet when outside of the Gnosis-safe iframe, it will get stuck on infinite loading.

Also the it should connect automatically when inside the gnosis-safe iframe

### PR DESCRIPTION
**Pull request by samuveth**
Fixes #29 

Changes proposed in this pull request:
- Prevent connecting with gnosis-safe when not inside a gnosis-safe iframe. This method of detecting was suggested by the gnosis team on the gnosis discord.
- Do not save gnosis-safe connector inside localStorage

### CODE REVIEW

File: connectors/gnosis.ts [hunk 1]
```diff
@@ -8,6 +8,9 @@ export default class Connector extends LockConnector {
   async connect() {
     let provider;
     try {
+      if (window?.parent === window) {
```
Comment (samuveth) [inline connectors/gnosis.ts:11]: @bonustrack We will still need this incase some already has the gnosis-safe connector saved inside their localStorage.

**Review by bonustrack — APPROVED** [review]
Looks good
